id: I9FB18349
legacy_id: P004438
ocr_import_info:
  bdrc_scan_id: W384
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T06:22:02'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T12:07:40.169088+00:00'
last_modified: 2022-09-03 20:13:24.425022
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W384
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW384
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། མཁས་གྲུབ་རྗེ། （ཞོལ་པར་མ། ལྡི་ལིར་བསྐྱར་པར་བརྒྱབ་པ།）
  author: མཁས་གྲུབ་རྗེ་དགེ་ལེགས་དཔལ་བཟང་།
statistics:
  ocr_word_mean_confidence_index: 0.6155487820857628
  ocr_word_median_confidence_index: 0.6399999856948853
quality: null
bases:
  I1KG956:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG956
      total_pages: 1186
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG956.txt
    statistics:
      ocr_word_median_confidence_index: 0.6399999856948853
      ocr_word_mean_confidence_index: 0.6156847659759977
    legacy_id: v001
  I1KG961:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG961
      total_pages: 942
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I1KG961.txt
    statistics:
      ocr_word_median_confidence_index: 0.5899999737739563
      ocr_word_mean_confidence_index: 0.5867008652148626
    legacy_id: v006
  I1KG960:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG960
      total_pages: 942
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I1KG960.txt
    statistics:
      ocr_word_median_confidence_index: 0.6399999856948853
      ocr_word_mean_confidence_index: 0.6157599062197393
    legacy_id: v005
  I1KG963:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG963
      total_pages: 890
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I1KG963.txt
    statistics:
      ocr_word_median_confidence_index: 0.6600000262260437
      ocr_word_mean_confidence_index: 0.6278352162602836
    legacy_id: v008
  I1KG957:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG957
      total_pages: 1118
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG957.txt
    statistics:
      ocr_word_median_confidence_index: 0.6499999761581421
      ocr_word_mean_confidence_index: 0.6192727487483203
    legacy_id: v002
  I1KG959:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG959
      total_pages: 1036
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1KG959.txt
    statistics:
      ocr_word_median_confidence_index: 0.6499999761581421
      ocr_word_mean_confidence_index: 0.6201676702981498
    legacy_id: v004
  I1KG962:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG962
      total_pages: 964
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I1KG962.txt
    statistics:
      ocr_word_median_confidence_index: 0.6100000143051147
      ocr_word_mean_confidence_index: 0.5964660736853824
    legacy_id: v007
  I1KG964:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG964
      total_pages: 990
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I1KG964.txt
    statistics:
      ocr_word_median_confidence_index: 0.6299999952316284
      ocr_word_mean_confidence_index: 0.6172355860887224
    legacy_id: v009
  I1KG966:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG966
      total_pages: 902
      volume_number: 11
      volume_pages_bdrc_intro: 2
    order: 11
    base_file: I1KG966.txt
    statistics:
      ocr_word_median_confidence_index: 0.6600000262260437
      ocr_word_mean_confidence_index: 0.632429915395419
    legacy_id: v011
  I1KG967:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG967
      total_pages: 946
      volume_number: 12
      volume_pages_bdrc_intro: 2
    order: 12
    base_file: I1KG967.txt
    statistics:
      ocr_word_median_confidence_index: 0.6499999761581421
      ocr_word_mean_confidence_index: 0.6239991856619275
    legacy_id: v012
  I1KG965:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG965
      total_pages: 1006
      volume_number: 10
      volume_pages_bdrc_intro: 2
    order: 10
    base_file: I1KG965.txt
    statistics:
      ocr_word_median_confidence_index: 0.6200000047683716
      ocr_word_mean_confidence_index: 0.6046250423686766
    legacy_id: v010
  I1KG958:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG958
      total_pages: 970
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG958.txt
    statistics:
      ocr_word_median_confidence_index: 0.6700000166893005
      ocr_word_mean_confidence_index: 0.6343498912157117
    legacy_id: v003
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
