id: I9FB18349
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T06:31:02+00:00'
last_modified: '2022-06-08T04:33:12.111197+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W384
  title: གསུང་འབུམ། མཁས་གྲུབ་རྗེ། （ཞོལ་པར་མ། ལྡི་ལིར་བསྐྱར་པར་བརྒྱབ་པ།）
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    DDF4:
      image_group_id: I1KG956
      title: ''
      total_pages: 1186
      order: 1
      base_file: DDF4.txt
    F661:
      image_group_id: I1KG957
      title: ''
      total_pages: 1118
      order: 2
      base_file: F661.txt
    DD7D:
      image_group_id: I1KG958
      title: ''
      total_pages: 970
      order: 3
      base_file: DD7D.txt
    36B8:
      image_group_id: I1KG959
      title: ''
      total_pages: 1036
      order: 4
      base_file: 36B8.txt
    CA1C:
      image_group_id: I1KG960
      title: ''
      total_pages: 942
      order: 5
      base_file: CA1C.txt
    62AE:
      image_group_id: I1KG961
      title: ''
      total_pages: 942
      order: 6
      base_file: 62AE.txt
    '3944':
      image_group_id: I1KG962
      title: ''
      total_pages: 964
      order: 7
      base_file: 3944.txt
    8E6E:
      image_group_id: I1KG963
      title: ''
      total_pages: 890
      order: 8
      base_file: 8E6E.txt
    B2B4:
      image_group_id: I1KG964
      title: ''
      total_pages: 990
      order: 9
      base_file: B2B4.txt
    69CA:
      image_group_id: I1KG965
      title: ''
      total_pages: 1006
      order: 10
      base_file: 69CA.txt
    BF81:
      image_group_id: I1KG966
      title: ''
      total_pages: 902
      order: 11
      base_file: BF81.txt
    0DF9:
      image_group_id: I1KG967
      title: ''
      total_pages: 946
      order: 12
      base_file: 0DF9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
